# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod Properties
maven_group=work.lclpnet.mods.gaco
mod_id=gaco
mod_version=0.16.0

minecraft_compat=1.21.11

# Dependencies
fabric_version=0.139.5+1.21.11
kibu-hook-api_version=1.4.0
kibu-hooks_version=0.64.0+1.21.11
kibu-scheduler-api_version=0.10.0+1.21.11
kibu-translation-api_version=0.26.0+1.21.11
kibu-schematic-api_version=0.10.1
kibu-schematic-fabric_version=0.14.0+1.21.11
kibu-assets-api_version=0.1.0

# subproject versions
gaco-dynamic-entities_version=0.1.1
gaco-ds_version=0.8.0
gaco-collisions_version=0.5.0
gaco-math_version=0.7.2
gaco-scene_version=0.1.0
gaco-core_version=0.1.0
gaco-scene-physics_version=0.1.0
gaco-asset-repo_version=0.4.4