pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'LCLPNetwork Maven'
            url = 'https://repo.lclpnet.work/repository/internal'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'gaco'
include 'gaco-dynamic-entities'
include 'gaco-ds'
include 'gaco-collisions'
include 'gaco-math'
include 'gaco-scene'
include 'gaco-core'
include 'gaco-scene-physics'