ext {
    kibuModules = [
            'kibu-schematic-api',
            'kibu-schematic-fabric',
    ]
    gacoModules = []
}

dependencies {
    def includeImpl = { dep ->
        implementation(dep)
        include(dep)
    }

    includeImpl(libs.ejml.core)
    includeImpl(libs.ejml.simple)
    includeImpl(libs.ejml.ddense)
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'gaco-math'
                description = 'Math utilities for game development'
            }
        }
    }
}
