ext {
    kibuModules = [
            'kibu-schematic-api',
            'kibu-schematic-fabric',
    ]
    gacoModules = []
}

dependencies {
    include(implementation("org.ejml:ejml-core:${project.ejml_version}"))
    include(implementation("org.ejml:ejml-simple:${project.ejml_version}"))
    include(implementation("org.ejml:ejml-ddense:${project.ejml_version}"))
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'gaco-math'
                description = 'Math utilities for game development'
            }
        }
    }
}
