ext {
    kibuModules = [
            'kibu-assets-api',
    ]
    gacoModules = [
    ]
}

dependencies {
    implementation(libs.sqlite.jdbc)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'gaco-asset-repo'
                description = 'Provides an API for interacting with asset repositories'
            }
        }
    }
}
