[versions]
minecraft = "26.1.2"
fabric-api = "0.147.0+26.1.2"
fabric-loader = "0.19.2"
fabric-loom = "1.16-SNAPSHOT"
gradle-build-tools = "1.7.0"
java = "25"
lombok = "9.4.0"
junit = "5.8.1"
jetbrains-annotations = "24.1.0"
mockito = "5.23.0"
sqlite-jdbc = "3.49.1.0+2025-07-12"
ejml = "0.44.0"
kibu-physics = "0.2.0+26.1.2"

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
java = { id = "java" }
gradle-build-utils = { id = "gradle-build-utils", version.ref = "gradle-build-tools" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-loader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric-loader" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
sqlite-jdbc = { module = "maven.modrinth:minecraft-sqlite-jdbc", version.ref = "sqlite-jdbc" }
ejml-core = { module = "org.ejml:ejml-core", version.ref = "ejml" }
ejml-simple = { module = "org.ejml:ejml-simple", version.ref = "ejml" }
ejml-ddense = { module = "org.ejml:ejml-ddense", version.ref = "ejml" }
kibu-physics = { module = "work.lclpnet.mods.kibu:kibu-physics", version.ref = "kibu-physics" }
