ext {
    kibuModules = [
    ]
    gacoModules = [
            "gaco-scene",
    ]
}

dependencies {
    implementation(libs.kibu.physics)
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'gaco-scene-physics'
                description = "Provides physics objects to the gaco-scene API"
            }
        }
    }
}
