ext {
    kibuModules = [
    ]
    gacoModules = [
            "gaco-scene",
    ]
}

dependencies {
    implementation("work.lclpnet.mods.kibu:kibu-physics:$project.kibu_physics_version")
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'gaco-scene-physics'
                description = "Provides physics objects to the gaco-scene API"
            }
        }
    }
}
